spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/message-event-db?replicaSet=myReplicaSet&authSource=admin
  threads:
    virtual:
      enabled: true
  elasticsearch:
    uris: localhost:9200

logging:
  level:
    org.springframework.transaction.interceptor: TRACE



server:
  port: 9090
