spring:
  application:
    name: demo
  data:
    mongodb:
      uri: mongodb://root:root@127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/message-event-db?replicaSet=myReplicaSet&authSource=admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group1

  threads:
    virtual:
      enabled: true

logging:
  level:
    org.springframework.transaction.interceptor: TRACE



server:
  port: 9090
