version: '3.8'
services:
  mongo1:
    image: mongo:latest
    hostname: mongo1
    container_name: mongo1
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
      - ./mongodb.key:/etc/mongodb.key
    networks:
     - cdc_default
    command: 'mongod --replSet myReplicaSet --keyFile /etc/mongodb.key --bind_ip_all --port 27017'
  mongo2:
    image: mongo:latest
    hostname: mongo2
    container_name: mongo2
    restart: always
    depends_on:
      - mongo1
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data2:/data/db
      - ./mongodb.key:/etc/mongodb.key
    networks:
     - cdc_default
    command: 'mongod --replSet myReplicaSet --keyFile /etc/mongodb.key --bind_ip_all --port 27018'
  mongo3:
    image: mongo:latest
    hostname: mongo3
    container_name: mongo3
    restart: always
    depends_on:
      - mongo2
    ports:
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data3:/data/db
      - ./mongodb.key:/etc/mongodb.key
    networks:
     - cdc_default
    command: 'mongod --replSet myReplicaSet --keyFile /etc/mongodb.key --bind_ip_all --port 27019'

networks:
  cdc_default:
    external: true
